[project]
name = "petra-smallgroups"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Luis Palacios", email = "lrpalaciosdev@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "pydantic>=2.13.4",
    "pydantic-settings>=2.15.0",
    "pyodbc>=5.3.0",
    "python-dotenv>=1.2.3",
    "sqlalchemy>=2.0.52",
]

[project.scripts]
petra-smallgroups = "petra_smallgroups:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pre-commit>=4.6.2",
    "ruff>=0.16.4",
    "ty>=0.0.73",
]
